version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app/src/
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    environment:
      GESTAO_HOST: 0.0.0.0
      GESTAO_DB_HOST: gestao-db
      GESTAO_DB_PORT: 5432
      GESTAO_DB_USER: gestao
      GESTAO_DB_PASS: gestao
      GESTAO_DB_BASE: gestao
      GESTAO_RELOAD: "True"

  db:
    image: postgres
    hostname: gestao-db
    environment:
      POSTGRES_PASSWORD: "gestao"
      POSTGRES_USER: "gestao"
      POSTGRES_DB: "gestao"
    volumes:
      - gestao-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U gestao
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    command: alembic upgrade head
    environment:
      GESTAO_DB_HOST: gestao-db
      GESTAO_DB_PORT: 5432
      GESTAO_DB_USER: gestao
      GESTAO_DB_PASS: gestao
      GESTAO_DB_BASE: gestao
    depends_on:
      - db

volumes:
  gestao-db-data:
    name: gestao-db-data
