def generate_fake_user():
    user = {
        "name": "joao",
        "address": "null",
        "neighborhood": "null",
        "city": "null",
        "state": "null",
        "zipcode": "null",
        "cpf": "null",
        "rg": "null",
        "birth_date": "2023-01-01",
        "place_of_birth": "null",
        "blood_type": "null",
        "gender": "null",
        "father_name": "null",
        "mother_name": "null",
        "position": "null",
        "occupancy": "null",
        "admission_date": "2023-01-01",
        "situation": "null",
        "phone": "null",
        "email": "joao@example.com",
        "marital_status": "null",
        "education": "null",
        "registration": "null",
        "role": "null",
        "category": "null",
        "pattern": "null",
        "dispatcher": "null",
        "dispatched_date": "2023-01-01",
        "war_name": "null",
        "password": "null",
        "rg_consignor": "null",
        "rg_date": "2023-01-01",
        "situation_obs": "null",
    }

    return user
